# Generated by Django 4.2.1 on 2023-06-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='tag',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
